ques = {
    1 : {'que' : 'Who developed Python Programming Language?',
         'a' : 'Wick van Rossum',
         'b' : 'Rasmus Lerdorf',
         'c' : 'Guido van Rossum',
         'd' : 'Niene Stom',
         'ans' : 'c'},
    2 : {'que' : 'Which type of Programming does Python support?',
         'a' : 'object-oriented programming',
         'b' : 'structured programming',
         'c' : 'funtional programming',
         'd' : 'all of the mentioned',
         'ans' : 'd'},
    3 : {'que' : 'Which of the following is the correct extension of the python file?',
         'a' : 'python',
         'b' : 'pl',
         'c' : '.py',
         'd' : '.P',
         'ans' : 'c'},
    4 : {'que' :'Is Python case sensitive when dealing with identifiers?',
         'a' : 'no',
         'b' : 'yes',
         'c' : 'machine dependent',
         'd': 'none of the mentioned',
         'ans' : 'b'},
    5 : {'que' : 'Is Python code compiled or interpreted?',
         'a' : 'Python code is both compiled and interpreted',
         'b' : 'Python code is neither compiled nor interpreated',
         'c' : 'Python code is only compiled',
         'd' : 'Python code is only interpreted',
         'ans' : 'a'},
    6 : {'que' : 'what will be the value of the following Python expression?\n\t 4 + 3 % 5',
         'a' : '7',
         'b' : '2',
         'c' : '4',
         'd' : '1',
         'ans' : 'a'},
    7 : {' que' : 'All keywords in Python are in_______',
         'a' : 'Capitalized',
         'b' : 'lower case',
         'c' : 'UPPER CASE',
         'd' : 'None of the mentioned',
         'ans' : 'd'},
    8 : {'que' : 'Which of the following is used to define a block of code in Python language?',
         'a' : 'Indentation',
         'b' : 'Key',
         'c' : 'Brackets',
         'd' : 'All of the mentioned',
         'ans' : 'a'},
    9 : {'que' : 'Which keyword is used for function in Python language?',
         'a' : 'Function',
         'b' : 'def',
         'c' : 'Fun',
         'd' : 'Define',
         'ans' : 'b'},
    10 : {'que' : 'Which of the following characters is used to give single-line comments in Python?',
          'a' : '//',
          'b' : '#',
          'c' : '!',
          'd' : '/',
          'ans': 'b'}
}